# Couleurs:
#
# Blanc = #F9F5F0
# Beige = #FFEED6
# Jaune = #E6B035
# Orange = #CC7700
# Rouge = #E66437
# Vert = #324D1E
# Vert_Fonc√© = #112600

[client]
showErrorDetails = "full"
toolbarMode = "auto"
showSidebarNavigation = true

[theme]
base = "dark"
primaryColor = "#CC7700"
backgroundColor = "#F9F5F0"
secondaryBackgroundColor = "#F9F5F0"
textColor = "#112600"
linkColor = "#324D1E"
redcolor = "#E66437"
orangeColor = "#CC7700"
yellowColor = "#E6B035"
blueColor = "#3778C2"
greenColor = "#324D1E"
violetColor = "#7F5AF0"
grayColor = "#6C757D"

font = "sans-serif"
baseFontSize = 16
baseFontWeight = 500
baseRadius = "medium"
buttonRadius = "full"
linkUnderline = false
showWidgetBorder = true

[theme.sidebar]
backgroundColor = "#324D1E"
secondaryBackgroundColor = "#F9F5F0"
textColor = "#F9F5F0"
