# Blanc: #F9F5F0
# Beige: #F2EAD3
# Orange: #F4991A
# Vert: #344F1F
# vert fonc√©: #1B2A0E

[client]
showErrorDetails = "full"
toolbarMode = "auto"
showSidebarNavigation = true

[theme]
base = "light"
primaryColor = "#F4991A"
backgroundColor = "#F9F5F0"
secondaryBackgroundColor = "#F9F5F0"
textColor = "#1B2A0E"
font = "sans-serif"
baseFontSize = 16
linkColor = "#F4991A"
linkUnderline = false
baseFontWeight = 500
baseRadius = "medium"
buttonRadius = "full"
#borderColor = "#344F1F"
showWidgetBorder = true

